# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Jorge de Castro
tagline:             ''
description:         '<img src="https://en.gravatar.com/userimage/119660097/439be0e970f6994179f475b1d3379526.jpg?size=350" style="border-radius: 25px;
                      padding: 10px;
                      "title="View on Gravatar" alt="View on Gravatar">'
url:                 http://jdecastroc.ovh
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jorge de Castro
  url:               https://twitter.com/mdo
  email:             jdecastrocabello@gmail.com

# Custom vars
version:             1.0.0

# Gems
gems:
- jekyll-paginate
- jekyll-archives
