# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               Jorge de Castro
tagline:             ''
description:         '<img src="http://www.gravatar.com/avatar/3c2986ad7ac1f2230ea3596f44563328?s=350" style="border: 10px solid transparent;
                      padding: 15px;
                      -webkit-border-image: url(border.png) 20% round; /* Safari 3.1-5 */
                      -o-border-image: url(border.png) 20% round; /* Opera 11-12.1 */
                      border-image: url(border.png) 20% round;"title="View on Gravatar" alt="View on Gravatar">'
url:                 http://jdecastroc.ovh
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jorge de Castro
  url:               https://twitter.com/mdo
  email:             jdecastrocabello@gmail.com

# Custom vars
version:             1.0.0

# Gems
gems:
- jekyll-paginate
- jekyll-archives
